### ISSUE TITLE
Wiki inaccessible after activating congrid template

### ISSUE THREAD

**Issue by residuocero** [LarsGit223/dokuwiki-template-congrid#1]
I have install 'congrid' template (compatible with DokuWiki 2018-04-22 "Greebo" according to https://www.dokuwiki.org/template ) and when I activated it my wiki crashed indicating "codification error" in web browser, making inaccesible it so I don't revert the template activation via web interface (access to files in server is neccesary).

**Comment by lpaulsen93** [comment]
Can you please describe what you mean with "Codification error"? In general if there is e.g. an error in the template config it should fallback to a default layout.

But in your situation it sounds like there in o way than changing back the config by hand (as you wrote by accessing the files on the server).

What exactly did you do? Did you change the templates configuration?

**Comment by lpaulsen93** [comment]
Just to be sure I tested the current version on my wiki without any modifications (I mean without changing the templates configuration) and it worked fine.

I am running DokuWiki Greebo on an Ubuntu 18.04 machine. My PHP version is 7.2.10.

**Comment by residuocero** [comment]
It is a dokuwiki 2018-04-22a "Greebo" in a free hosting, I installed the followings plugins using Plugin Manager (within code changes): autologoff, BackupTool, Bureaucracy, Changemark, Changes, color, CSV, denyactions, Doodle3, dtable, edittable, iCalEvents, Login/Logout logging, OpenLayersMap, Redirect, statdisplay, TabTables, tplmod, DokuWiki Upgrade, Video Share. I installed 'congrid' using Plugin Manager (so within code changes). When I activated 'congrid' as template, the website became inaccessible indicating "codification error" as error message in the center of the web browser tab (refreshing Firefox tab or opening in other web browser as TorBrowser I got the same error). The only solution was to access the hosting via FTP and delete the folder 'congrid' and then again refresh the tab so I could see the (fallback?) Configuration Menu. I tried the templates 20cones, bootstrap3, congrid, icke, material, sprintdoc, arctic, codowik, flat, Twenty Fifteen, wallpaper, Zenith, dokubook, dokucms, dokukit, stm, mnml and ramtop in this order, only congrid gave this problem and the rest of templates well displayed except that the Zenith template looked ugly I think I remember that indicating a CSS error at the top. I do not know the OS distribution or PHP version that this hosting uses, I'm sorry.

**Comment by lpaulsen93** [comment]
Ok, thanks for the info.

I did not have that problem yet. I fixed an issue lately in #2 but that did not make the wiki break. As you have not changed the congrid template's configuration I assume it has something to do with some of the plugins. I will test and report the results.

**Comment by lpaulsen93** [comment]
I do not get an error from just installing the plugins. My wiki still works.

Maybe it has to do with the PHP version being used. You can check it in this way:
- enable the config option ```allowdebug```
- open a wiki page and append ```&do=debug``` in the browsers address bar and hit return
- a page with a lot of debug output will appear

Search for an entry like this:
```
PHP Version:

7.2.10-0ubuntu0.18.04.1
```
**After that, disable the config option ```allowdebug```.**

Also it might help if you could post some example content of a page that breaks (most plugins only do something if the wiki page contains a syntax tag which calls the plugin).

**Comment by lpaulsen93** [comment]
It would also be nice to know which browser you used and maybe you could post a screenshot from the broken wiki as I do not yet understand what  "Codification error" means. Thanks for all your help so far.

**Comment by residuocero** [comment]
I see the 'allowdebug' option but I can not activate it, probably as a security measure of the free hosting. I'm sorry.

The Firefox error message is this:  https://prod-cdn.sumo.mozilla.net/uploads/images/2017-06-08-11-29-07-679a8c.png   and   https://prod-cdn.sumo.mozilla.net/uploads/images/2012-06-16-05-31-46-9bfac7.png   (practically does not provide details). All my wiki pages (not only Config page) showed the same error that made them inaccessible.

Just in case this information helps you something (I feel that little information I can bring you) I indicate that my website is in Spanish and I connect to the Internet using Ethernet cable.

Given the limited information that I can unfortunately contribute, that may be due to an error in an old PHP version and that it seems that you are not able to reproduce the error, if you consider it appropriate you can close the topic as "not reproducible", "insufficient information" or whatever you deem appropriate.

**Comment by lpaulsen93** [comment]
I am also using Firefox Version 64.0. Which version are you using?

You might get more information from Firefox if you press ```Shift+F5``` and click on the "Console" window.

As the template page at dokuwiki.org explains my template uses the CSS grid layout which is quite new. See https://www.w3schools.com/css/css_grid.asp. According to that webpage it requires at least Firefox version 52.0.

Maybe that's the problem and not the PHP version.

**Comment by residuocero** [comment]
Well, possibly that's it. I am using Firefox 45.9 because the damn breaks between versions makes me lose my tabs and bookmarks so I have postponed upgrading. It had not occurred to me that it could be the cause of the problem (a lot of CMS and respective templates tested without problems caused by this), otherwise I would have saved you the trouble. That being so, for me you can close the topic, with my only suggestion of if it is possible plus you have time and desire then to introduce some mechanism that allows to load an alternative compatible fallback CSS so that nobody happens to me (the error makes the wiki inaccessible from the web interface). I appreciate a lot your time and attention. Best wishes!

**Comment by lpaulsen93** [comment]
I have to check if that's possible.

I do not want to insert a compete fallback CSS in my template because that would basically mean to have another template in my template only as a fallback. Maybe at the start of a page request I can check the browser version (if possible) and fallback to the standard DokuWiki template and report an error message to the user. That sounds more feasible to me.

So, I will close this as an incompatibility issue which will not be fixed. I also created an issue for the enhancement, see #3.

Thanks for giving the template a chance and for providing all the information :+1:
